language: objective-c

before_install:
  - export PROJECT_DIR=$(pwd)

install:
  - cd $HOME
  - git clone https://github.com/google/bazel
  - cd bazel
  - ./compile.sh
  - export PATH="$PATH:$HOME/bazel/output"

before_script:
  - cd $PROJECT_DIR

script:
   - blaze build :all
